#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_HEADER="${SCRIPT_DIR}/tls_local.h"

SUBJECT="${TLS_SUBJECT:-/CN=miniscreen.local}"
DAYS="${TLS_DAYS:-3650}"

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl not found. Install OpenSSL and rerun this script." >&2
  exit 1
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

KEY_PEM="${TMP_DIR}/server.key"
CERT_PEM="${TMP_DIR}/server.crt"

openssl ecparam -name prime256v1 -genkey -noout -out "${KEY_PEM}"
openssl req -new -x509 -key "${KEY_PEM}" -out "${CERT_PEM}" -days "${DAYS}" -subj "${SUBJECT}"

{
  cat <<'EOF'
#pragma once
// This file is auto-generated by generate_tls_cert.sh.
// Do not commit this file to a public repository.

static const char serverCert[] PROGMEM = R"EOF(
EOF
  cat "${CERT_PEM}"
  cat <<'EOF'
)EOF";

static const char serverKey[] PROGMEM = R"EOF(
EOF
  cat "${KEY_PEM}"
  cat <<'EOF'
)EOF";
EOF
} > "${OUT_HEADER}"

echo "Generated ${OUT_HEADER}"
